controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# Path: src/Controller/CommentMatchController.php
match_view:
    path: /matchsList/match/{id}
    controller: App\Controller\CommentMatchController::view